### ISSUE TITLE
[Question] How to deploy a runnable JAR?

### ISSUE THREAD

**Issue by copycat-killer** [jacamo-lang/jacamo#11]
This might be a trivial question, still I'm not able to figure it out.

Could you please tell me the exact steps to do in order to create a runnable, self-contained JAR?

For instance, assume you have the hello-world example project. How do you create a JAR that you can launch just with `java -jar ...` and get "hello world" printed? Thanks in advance.

**Comment by jomifred** [comment]
Hi Luke, 

this is a feature available in Jason that wasn't implemented in JaCaMo yet. I will try to do that soon.

**Comment by copycat-killer** [comment]
Thank you.

Actually, I found [this](http://jason.sourceforge.net/faq/#_how_to_run_my_application_without_jason_ide). It works, but the autogenerated xml does not include a `jar` option.

**Comment by jomifred** [comment]
Hi, I've just changed jason/moise/jacamo to support the creation of single jars for jacamo applications, as it exits for Jason. Since a lot of files were changed, I produced a new release for jacamo at 

https://sourceforge.net/projects/jacamo/files/version-0

with all files. Of course, github sources were also updated.

**Comment by copycat-killer** [comment]
Thanks.
