### ISSUE TITLE
Unable to run GoldMiner tutorial file

### ISSUE THREAD

**Issue by pulverizers** [jacamo-lang/jacamo#22]
I downloaded the project file from : http://jacamo.sourceforge.net/tutorial/gold-miners/initial-gold-miners.zip and import it in eclipse. However, running the Jacamo program doesn't work: 

![image](https://user-images.githubusercontent.com/8087472/47292277-60f6da00-d5fe-11e8-8f7e-bfb7566927cc.png)

**Comment by jomifred** [comment]
Hi, It is likely due to the use of an old release of jason.jar. I’d suggest to update to the lastest jacamo release from
	https://sourceforge.net/projects/jacamo/files/version-0/

or use eclipse “File/Import” and “existing gradle project” (eclipse Photon (EE) has gradle integrated). For this latter option, I updated the initial-gold-miners.zip file with a gradle script. With gradle, issues related with jason versions are easier solved.

Best

Jomi

> On 22 Oct 2018, at 09:29, bangxiang <notifications@github.com> wrote:
> 
> I downloaded the project file from : http://jacamo.sourceforge.net/tutorial/gold-miners/initial-gold-miners.zip and import it in eclipse. However, running the Jacamo program doesn't work:
> 
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)
