### ISSUE TITLE
License discrepancies

### ISSUE THREAD

**Issue by Addy90** [jacamo-lang/jacamo#3]
Sorry to bother again but I found a big discrepancy in your License model which can and will be a big problem in how one can use JaCaMo.

On your website, you say that JaCaMo is licensed under LGPL (see http://jacamo.sourceforge.net/).
Also, Jason is indeed licensed under LGPL on GitHub.
BUT since JaCaMo 0.6, you introduced the GPL which also is used in CArtAgO and MOISE on GitHub.

Moreover when you search in this repository after "Lesser" for example, you find several source files that indeed are under LGPL, like f. e. https://github.com/jacamo-lang/jacamo/blob/master/src/main/java/jacamo/infra/JaCaMoLauncher.java

Can you please fix that discrepancy? It will lead to problems when you start using JaCaMo while thinking it is LGPL while in reality it is not. Thank you a lot!

**Comment by rbordini** [comment]
Hi Adrian,

Thanks for letting us know about you and thank you for considering 
JaCaMo for your work!

We agreed sometime ago that Cartago and Moise would move to LGPL, like 
Jason has always been, so that there would be no such discrepancy. That 
is the ideal and sorry if some files are not yet updated but feel free 
to start using it as it is, then later when we update the licenses you 
can download it again.

Best,

Rafael

**Comment by Addy90** [comment]
Hi Rafael,

alright, I was not sure which licence JaCaMo would move to but thanks to your explanation, I know that you are planning to move to LGPL sooner or later.

Thank you for that information :) Already solves a lot of insecurity!
